### PR TITLE
Remove pins/extra channels from environment.yaml

### LINKED ISSUE #4: No longer runs
As noted by https://twitter.com/dschneiderch/status/1380208965682753539 , this no longer runs on binder at all. The blog is, of course, old, but it may be worth updating the environment.

### PR DESCRIPTION
**Pull request by jsignell**
Closes #4

### CODE REVIEW

**Comment by martindurant** [comment]
Thank you!

**Comment by jsignell** [comment]
I ran the notebooks and made some minor tweaks to comply with latest versions.

**Comment by martindurant** [comment]
Looks good - seems the world has moved a bit in the last two years.

**Comment by jsignell** [comment]
Yeah I was impressed how little it moved actually! Glad you settled the great `Catalog` vs `open_catalog` debate :)

**Pull request merged**
